# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = ENV.fetch("VAGRANT_BOX", "ubuntu/trusty64")

  {
    "am-local" => {
      "ip" => "192.168.168.192",
      "memory" => "2048",
      "cpus" => "2",
    },
  }.each do |short_name, properties|

    # Define guest
    config.vm.define short_name do |host|
      host.vm.network "private_network", ip: properties.fetch("ip")
      host.vm.hostname = "#{short_name}.myapp.dev"
    end

    # Set the amount of RAM and virtual CPUs for the virtual machine
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", properties.fetch("memory")]
      vb.customize ["modifyvm", :id, "--cpus", properties.fetch("cpus")]
    end

  end

  # Make the project root available to the guest VM
  config.vm.synced_folder '.', '/vagrant'

  # Ansible provisioning
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./singlenode.yml"
    ansible.host_key_checking = false
    ansible.extra_vars = {
      "archivematica_src_dir" => "/srv",
      "archivematica_src_environment_type" => "development",
    }
    #ansible.raw_arguments = ENV['ANSIBLE_ARGS']
    # accept multiple arguments, separated by colons
    ansible.raw_arguments = ENV['ANSIBLE_ARGS'].to_s.split(':')
    ansible.skip_tags = ["amsrc-pipeline-clonecode", "amsrc-ss-clone"]  # Mounted below
  end

  config.vm.synced_folder "/home/holly/work/artefactual/archivematica", "/srv/archivematica/"
  config.vm.synced_folder "/home/holly/work/artefactual/archivematica-storage-service", "/srv/archivematica-storage-service/"
  config.vm.synced_folder "/home/holly/work/artefactual/appraisal-tab", "/srv/appraisal-tab/"

end
